#!/usr/bin/env python
"""
This executable script is part of the plotfile-viewer package.

It automatically creates a new pre-filled IPython notebook
in the local directory, and opens it in a browser.

Usage: Simply type `plotfile_notebook` in a regular terminal
"""
import os
from importlib import resources


def main():
    """Create the template notebook locally and launch Jupyter."""
    template_path = (resources.files('plotfile_viewer')
                     / 'notebook_starter'
                     / 'Template_notebook.ipynb')
    notebook_text = template_path.read_text()

    with open('./plotfile-visualization.ipynb', 'w') as notebook_file:
        notebook_file.write(notebook_text)

    os.system('jupyter notebook plotfile-visualization.ipynb')


if __name__ == '__main__':
    main()
